### ISSUE TITLE
Add alt property to the img tags for 508 compliance

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/mutation-mapper#37]

**Comment by pieterlukasse** [comment]
hi @onursumer does this apply to both `mutationMapper.js` and `mutationMapperTemplates.html`? Then we also need to take the changes on both these files made in https://github.com/cBioPortal/cbioportal/pull/1219

**Comment by pieterlukasse** [comment]
@onursumer , @jjgao : how can we orchestrate this? It is high priority for us.

**Comment by onursumer** [comment]
Hi @pieterlukasse. Yes, this applies to both files. But, I don't see any changes in `mutationMapper.js` within https://github.com/cBioPortal/cbioportal/pull/1219.

The best way to manage mutation mapper changes is to create pull requests on this repository. Then I can rebuild the binaries and update the corresponding cbioportal branch (rc or hotfix).

Also note that, in this repository no one should directly modify the files in the https://github.com/cBioPortal/mutation-mapper/tree/master/build directory.

**Comment by onursumer** [comment]
Please create the PR on the https://github.com/cBioPortal/mutation-mapper/tree/rc branch. Files that need to be modified are located here: https://github.com/cBioPortal/mutation-mapper/tree/rc/src/html

**Comment by pieterlukasse** [comment]
thanks @onursumer . @fedde-s will work on this.
