### ISSUE TITLE
Bug in mutationMapper.js dataFieldCount method

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/mutation-mapper#39]
While debugging I noticed that the retrieved data is available in a different format than expected by the mutationMapper.js `dataFieldCount` method. See screenshot. All attributes are available in an "attributes" list variable and _not_ directly under `mutations[i]`  (so `mutations[i].attributes["uniprotAcc"]` works while `mutations[i]["uniprotAcc"]` fails)

![image](https://cloud.githubusercontent.com/assets/2900303/15572464/1be0b8cc-2341-11e6-8330-7597c0c78aaf.png)

**Comment by pieterlukasse** [comment]
I did a quick check and it looks like the backend code `MutationDataUtils.getMutationData()` has not  changed recently.

**Comment by pieterlukasse** [comment]
perhaps the fix is something like `mutations.at(i).get(dataField)` like changed recently elsewhere in the code? For example: 

``` javascript
    this._updateGeneMap = function(mutations)
    {
        var mutationMap = _mutationGeneMap;

        // process raw data to group mutations by genes
        for (var i=0; i < mutations.length; i++)
        {
            var gene = mutations.at(i).get("geneSymbol");
```

**Comment by onursumer** [comment]
Thanks for reporting this @pieterlukasse! Looks like this is related to recent data field access method change on the front-end. I will try to fix this soon.
