### ISSUE TITLE
Incorrect help text in mutations view

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/mutation-mapper#43]
All the columns in the mutation view display the same help text on hover:

![image](https://cloud.githubusercontent.com/assets/2900303/15649444/e20497f2-2671-11e6-9252-d217908359fd.png)

**Comment by onursumer** [comment]
This is really weird. It works fine in the standalone debug page of mutation mapper. Different qTip library version, portal specific configuration, etc. might be the reason.

**Comment by pieterlukasse** [comment]
or maybe a bug in the build process of the library?

**Comment by pieterlukasse** [comment]
when I test on /beta release, I see the items repeated in the html code as well. See screenshot:

![image](https://cloud.githubusercontent.com/assets/2900303/15739069/9ea1cae0-28ae-11e6-9aac-ce465fe7bba6.png)

**Comment by onursumer** [comment]
It doesn't seem like a build error to me. That part of the html is dynamically generated by the qTip library. This is most likely a bug in the JS code where we initialize/generate the qTip content.

**Comment by pieterlukasse** [comment]
Ok, so it needs to be fixed here, or do you suspect some other part of the portal?

**Comment by onursumer** [comment]
@pieterlukasse: The problem was the incorrect initialization of the qTip instances in the mutation mapper library.
