### ISSUE TITLE
Resize columns in table

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/mutation-mapper#68]
I got this request from a user: it would be nice to be able to allow users to resize the columns in the mutation view table.

**Comment by pieterlukasse** [comment]
@jjgao , @alisman any thoughts on this one?

**Comment by alisman** [comment]
Did the say what specific use case is?  No doubt it would be a nice feature but I think we have to weigh the cost.

**Comment by pieterlukasse** [comment]
Not sure anymore. Could be related to RFC45 (https://docs.google.com/document/d/1X7dA_wJFtv5xJO1oHCSt8DUdTmk07RexvHUpjCJsSM4/edit#heading=h.t3nbi7llssq7)

**Comment by jjgao** [comment]
I wouldn't prioritize this unless it's really easy. @alisman

**Comment by alisman** [comment]
Unfortunately, it's not too easy.  This would be something we would want from a table library.   For better or worse, after a lot of deliberation, we decided to use our own library.   If there are enough features we really need, we can reconsider that decision.   My guess is it would be 3-4 week project to switch.

**Comment by jjgao** [comment]
@pieterlukasse I'll close this one until we have a strong use case.
